src/ffishjs.cpp
tests/js/README.md
tests/js/package.json
tests/js/test.js

Hello @ianfab ,
due to a request by @gbtami who wants to use the [ffish.js library](https://github.com/ianfab/Fairy-Stockfish/tree/master/tests/js) for the [pychess-variants server](https://www.pychess.org/), I created an official [npm-package](https://www.npmjs.com/package/ffish) for it. The library has an unpacked size of 692 kB including the wasm file and 0 dependencies.
Moreover, I updated [package.json](https://github.com/QueensGambit/Fairy-Stockfish/blob/ffish_js/tests/js/package.json) accordingly and added a `ffish.info()` method which returns the version of the _Fairy-Stockfish_ binary.
I discovered that some js frameworks like [vue-js](https://vuejs.org/) require a wasm library to be exported as an [ES2015](https://en.wikipedia.org/wiki/ECMAScript) module …

Updated ffish.js for initial npm version

---

tests/js/README.md
tests/js/package.json
tests/js/test.js

Hello, I build ffish.js with large board support for version 0.1.5 on [npm](https://www.npmjs.com/package/ffish/v/0.1.5).
I needed to add the following flags to emcc to achieve this:
```
-s TOTAL_MEMORY=67108864 -s ALLOW_MEMORY_GROWTH=1 \
-s WASM_MEM_MAX=2147483648 -DLARGEBOARDS -DPRECOMPUTED_MAGICS \
```
Without the memory flags it resulted in an OOM error and without `-DPRECOMPUTED_MAGICS` it resulted in a timeout.
The file [test.js](https://github.com/ianfab/Fairy-Stockfish/pull/176/files#diff-f2e05ad09d88ee9a8211493d42c470ef) also covers a test for a large board, here Xiangqi.

added -DLARGEBOARDS support

---

Readme.md
src/ffishjs.cpp
tests/js/README.md
tests/js/package.json
tests/js/test.js

Hello @ianfab  and @gbtami ,
I added the requested functionality from #177 resulting in **ffish.js v0.2.0**.
Is now available as a static method. Because you can only overload methods based on the number of arguments from emscripten and not based on variable type, I exported additional methods for integer and boolean options.
However, loading files from JavaScript is tricky and unavailable for browsers.
It seems you require the [filesystem-API](https://emscripten.org/docs/api_reference/Filesystem-API.html#including-file-system-support) for that because I receive: `Unable to open file variants.ini` when setting the `VariantPath`.
Perhaps it is better to add an additional method just for parsing a `variant.ini`-string without reading the file within the library.
- ffish.setOption()
- …

Added functionality to ffish.js (closes #177)

---

tests/js/package.json

because of bugfix in FairyStockfish (#207, 186eeb0a56c942da54f77d53a7eb1e2ce067e13b).

Updated ffish.js to 0.4.7

---

src/ffishjs.cpp
tests/js/README.md
tests/js/package.json
tests/js/test.js
tests/pgn/Syrov - Dgebuadze.pgn

Hi @ianfab ,
we noticed that **ffish.js@0.4.7** was giving faulty mainlines when parsing pgn strings with nested alternative move lines and glyph annotations. The release **ffish.js@0.5.0** aims to fix this behaviour.
* fixed parsing **ffish.readGamePGN(pgn)** when reading pgns with alternative nested move lines and
glyphs. The pgn-file `Syrov - Dgebuadze.pgn` was added for unit testing.
* mapped variant `"standard"` and `"Standard"` to `"chess" `
* **board.toString()** it returns a compact string representation of the board (example was added to **README**).
* **board.toVerboseString()** it returns a verbose string representation of the board (example was added to **README**).
Apparently, _FairyStockfish's_ move generation ordering has changed:
```javascript
const board = new …
```

Upgraded ffish.js to 0.5.1, fixed ffish.readGamePGN(pgn), added toString() methods

---

README.md
src/evaluate.cpp
src/parser.cpp
src/position.cpp
src/position.h
src/psqt.cpp
src/ucioption.cpp
src/variant.cpp
src/variant.h
src/variants.ini

Add variant nocheckatomic which implements a modified version
of atomic chess where check and check-/stalemate do not apply,
which is very similar to the rules used on ICC.
The variant atomic is an incomplete implementation of
lichess atomic chess rules, added for easier usage in GUIs.
It will occasionally play illegal moves in this variant.

Support atomic chess without checks (#81)

---

src/apiutil.h
src/ffishjs.cpp
tests/js/README.md
tests/js/package.json
tests/js/test.js

Hi @ianfab ,
I noticed that you integrated atomic into Fairy-Stockfish (https://github.com/ianfab/Fairy-Stockfish/pull/238 ).
Many people will enjoy using it in **ffish.js@0.6.0**, too.
* **ffish.readGamePGN(pgn)** sometimes pushed  `{` as SanMoves. This is now fixed by incrementing `curIdx`.
*  **ffish.validateFen()** is more robust now and allows the placeholder `-` for variants which do not have a no-progress counter or castling rights. The unit tests have been extended accordingly to also check the fen after a board object has been created using the starting-fen.
* **board.variant()** it returns the uci-variant of the board.
* **board.push()**, **board.pushSan()**, **board.sanMove()**, **board.variationSan()** now inform the user via _stderr_ if a given move is invalid and will return …

Updated ffish.js to 0.6.0, fixes ffish.validateFen(), ffish.readGamePGN(pgn), added board.variant(), atomic support

---

src/parser.cpp
src/position.cpp
src/position.h
src/variant.cpp
src/variant.h
src/variants.ini
tests/perft.sh

This implements support for pseudo-royal pieces,
which allows to now fully support some new variants:
- lichess atomic rules
- coregal chess
- maharajah and the sepoys
Closes #81.
No functional change for other variants.

Support pseudo-royal pieces

---

src/material.cpp
src/parser.cpp
src/position.cpp
src/position.h
src/variant.cpp
src/variant.h
src/variants.ini

This supersedes manual definition of the endgame evalution flag.
For a few variants the automatically calculated flag now enables
endgame evaluation where before it was explicitly disabled.
losalamos STC
LLR: 2.97 (-2.94,2.94) [-10.00,5.00]
Total: 1151 W: 292 L: 253 D: 606
http://www.variantfishtest.org:6543/tests/view/6044ea416e23db669974ea05
Closes #271.

Precalculate endgameEval flag

---

src/search.cpp
src/ucioption.cpp

Extends UCI_Elo range to support negative Skill Levels also via corresponding UCI_Elo values.
Edit: In a short test the correlation between UCI_Elo and ordo rating looks good. 
```
1 1400      :  1400.0    47.0      56    84
2 1200      :  1376.7    46.0      56    82
3 1000      :  1365.2    45.5      56    81
4 900       :  1102.9    34.0      56    61
5 800       :   803.0    22.0      56    39
6 700       :   583.6    12.5      56    22
7 600       :   502.6     9.0      56    16
8 500       :   478.3     8.0      56    14
```

Support lower UCI Elo levels

---

.github/workflows/fairy.yml
src/Makefile
src/Makefile_js
src/evaluate.cpp
src/evaluate.h
src/nnue/evaluate_nnue.cpp
src/nnue/features/half_ka_v2.cpp
src/nnue/features/half_ka_v2.h
src/nnue/features/half_ka_v2_shogi.cpp
src/nnue/features/half_ka_v2_shogi.h
src/nnue/features/half_ka_v2_variants.cpp
src/nnue/features/half_ka_v2_variants.h
src/nnue/layers/affine_transform.h
src/nnue/layers/clipped_relu.h
src/nnue/nnue_accumulator.h
src/nnue/nnue_architecture.h
src/nnue/nnue_common.h
src/nnue/nnue_feature_transformer.h
src/search.cpp

* Requires to train corresponding variant nets to not lose NNUE support for variants where HalfKP nets already are available.
* Disable NNUE lazy eval for variants?

Merge HalfKAv2 architecture

---

tests/js/package.json

As suggested in  Fix variant initialization for libraries.
* https://github.com/ianfab/Fairy-Stockfish/commit/78700852f96db30149f1105f80364d092d12d90f
This PR only changes the version id.
New libraries are already published on npm:
* https://www.npmjs.com/package/ffish

Updated ffish.js to 0.6.2

---

src/position.cpp

This fixes a bug with how blasting in atomic affects castling rights' keys.
reproduction:
turn off Fast in `pos_is_ok`
run in debug:
```
xboard
variant atomic
setboard 7k/8/8/7q/8/8/7P/4K2R b K - 0 1
usermove h5h2
```
the key will differ when recalculated

Fixed blasted pieces incorrectly updating key's castling rights

---

src/evaluate.cpp
src/variant.cpp
src/variant.h

Define aliases for compatible variants, so that they can re-use existing NNUE files without requiring to create symlinks or copies of the evaluation files.

Support re-usage of NNUE nets for other variants

---

src/nnue/features/half_ka_v2_variants.cpp
src/position.cpp

This allows to apply incremental NNUE computation not only to drop variants,
but also to S-Chess gating and drop variants with blast captures.

Generalize incremental computation for hand pieces

---

src/uci.cpp

Hi, thanks for making Fairy-Stockfish! I've been enjoying using it.
I'm just making this pull request to put this out there if anyone is interested. I've been messing around with custom variants, and think it would be convenient to not need to specify the load command if you keep your variants file in the same place. This PR will have Fairy-Stockfish check the environment variant `FAIRY_STOCKFISH_VARIANT_PATH`, and if it exists, it will load the file at this path as the variant config. This will get overridden by a "load" command on the command line.
I tested it on Windows 10 and Linux Mint 20.2, and it works pretty well!
I have a question though, and maybe it should go in an issue. I noticed that the "load" command, when entered as a command line arg or in the UCI loop, cannot handle …

Autoload variants.ini if specified in by an environment variable

---

src/evaluate.cpp
src/uci.cpp
src/uci.h
src/ucioption.cpp

* Allow whitespace characters in `load` command.
* Support loading of multiple files separated by `:`/`;`.
Closes #361.

Support spaces in variants.ini path

---

src/nnue/features/half_ka_v2_variants.cpp
src/nnue/features/half_ka_v2_variants.h
src/nnue/nnue_feature_transformer.h
src/position.h
src/variant.h

This adds dedicated NNUE support for variants where kings
only have access to a limited set of squares, like Xiangqi,
or are missing entirely, like in antichess.
Closes #346.

Support NNUE with varying king dimensions

---

src/position.cpp
test.py

Implements the rules as clarified by Sahapol Nakvanich, the current president of Thailand Chess Association:
- Khon and Knight don't need a Met to start counting
- Counting only starts after all pawns are promoted

Correct ASEAN's counting rules

---

setup.py
src/apiutil.h
src/pyffish.cpp
test.py

In WXF notation +/- disambiguation can be ambiguous when there is more than one tandem of pieces/pawns.
Closes #395.

Use tandem pawn notation for double tandems

---

src/uci.cpp

Commit b01c9ab does not fix #412, so I tried to debug it. This should fix #412 now.

Fix search for option aliases in UCI dialects

---

src/movegen.cpp
src/pawns.cpp
src/position.cpp
src/variant.cpp
src/variants.ini
test.py

Handle mandatory pawn promotion more naturally by removing
the promotion rank workaround for Sittuyin and instead
explicitly disable rank based promotion in case of sittuyin promotion.

Sittuyin promotion disables rank based promotion

---

tests/js/package.json

Bumped version to 0.6.5 as requested in https://github.com/ianfab/Fairy-Stockfish/issues/408.
Releases are available on **npm** using today's commit.
* https://www.npmjs.com/package/ffish

Bump ffish to 0.6.5

---

src/uci.cpp

Use here-docs to load variant configurations from the CLI.
```
load <<EOF
[testvariant:chess]
somerule = somevalue
EOF
```

Support variant config parsing on CLI

---

src/variants.ini

1. Addition of Campmate rules in Pandemonium
2. Addition of a new chess variant, Parahouse
I would like to ask you two things.
//
Regarding number 1,
[pandemonium]
variantTemplate = shogi
pieceToCharTable = PNBRFSA.UV.++++++++.++Kpnbrfsa.uv.++++++++.++k
maxFile = 9
maxRank = 9
pocketSize = 9
startFen = rnbsksbnr/2+f1+u1+a2/p1p1p1p1p/4v4/9/4V4/P1P1P1P1P/2+F1+U1+A2/RNBSKSBNR[] w - - 0 1
customPiece1 = o:NA
customPiece2 = s:WF
customPiece3 = u:D
customPiece4 = w:DWF
cast = false
pieceDrops = true
capturesToHand = true
immobilityIllegal = true
soldier = p
knight = n
bishop = b
rook = r
king = k
queen = q
commoner = g
dragonHorse = h
bers = d
alfil = a
archbishop = c
chancellor = m
fers = f
wazir = v
centaur = t
promotionRank = 7
promotedPieceType = p:g n:o b:h r:d a:c v:m f:q s:w u:t …

Fixed Pandemonium, added Parahouse (new variant)

---

src/movegen.cpp
src/position.cpp
src/position.h
src/variant.cpp
src/variant.h
tests/perft.sh

For some games like Ataxx and Othello, specifying the pieces in hand is unnecessary. Setting freeDrops to true removes this from the FEN string.

Implement Variant::freeDrops

---

README.md
src/variant.cpp

I'm trying to help Miguel Illescas popularise this variant, and adding support to Fairy-Stockfish would be a good step in that direction. I'm planning to train an NNUE evaluation for this variant soon, too.
Phenomenal project, by the way! Back when I started writing the program that eventually became Stockfish, I couldn't in my wildest dream imagine that it would some day develop into something as awesome as this. Thank you so much for your work!

Add in-built support for Miguel Illescas' Dragon Chess.

---

src/parser.cpp
src/position.cpp
src/position.h
src/types.h
src/variant.cpp
src/variants.ini
test.py

According to Article 5, Item 5 of this document.
https://docs.google.com/document/d/1adppJ66vonM27UYwC-KyldXl7oZ_5Pb0/edit?usp=sharing&ouid=116281580550740302191&rtpof=true&sd=true
To summarise the differences from Makruk:
1. The game ends in a draw immediately when the counting limit is reached, instead of exceeded. This effectively reduces the counting limit by one move.
2. The condition for a player to start board's honour counting is having three pieces or less, regardless of the number of unpromoted pawns on the board.
3. When the condition for piece's honour counting is met, the counting player may choose not to go into it, and continue the board's honour counting instead. This is be implemented by automatically choosing the method that can reach the counting limit in less number of …

Implement Ouk Chaktrang's counting rules

---

tests/js/package.json

New ffish version 0.6.9 because Cambodian rules in Fairy-Stockfish have been implemented.
Packages are available on
* https://www.npmjs.com/package/ffish
* https://www.npmjs.com/package/ffish-es6

Bump ffish version to 0.6.9

---

setup.py
src/pyffish.cpp

Ada already published a new pyffish (source only!) package with this version on PYPI, but seems the version bump was missing from her latest PRs.
That 0.0.73 pyffish is a source only release, causing your FairyFishGUI pyinstaller action fail (because there are no wheels for latest pyffish in pypi, just the source). All in all I want to remedy this, and upload the missing pyffish wheels.

Bump pyffish version

---

src/xboard.cpp

Adding remove command xboard sends when pressing Ctrl+X, only sent when player's turn, go back two moves to players previous turn. Allows player to go back and try different moves without engine stopping like undo, see https://www.gnu.org/software/xboard/engine-intf.html#8 for differences between undo and remove. 
From xboard debug file, when trying to retract move with Ctrl+X
```
13827 >first : remove
13829 <first : Error (unknown command): remove
```
Currently 'remove' is an unknown command to Fairy-SF and there's a distinction in the xboard protocol between undo and remove. I've had issues when trying to retract and play different moves against the engine. This is my hacky solution, I just copied the undo code and call undo_move() twice. Calling it once or using undo doesn't work, the …

Update xboard.cpp - remove command

---

src/Makefile

A trivial improvement from upstream:
```
bmi1 enables the use of _blsr_u64 for pop_lsb, and is availabe when avx2 is.
verified a small speedup (0.2 - 0.6%)
closes https://github.com/official-stockfish/Stockfish/pull/4202
No functional change
```

enable bit manipulation instruction set 1

---

tests/js/README.md

Hi! Small pull request.
Heroku is ending support for free dynos, and my example "ffish-test" project was being hosted there. It only needed to serve static assets anyways, so I got it running on GitHub pages now. This PR updates the project link to the new deployment link.
CC @QueensGambit

Update ffish-test deployment link

---

README.md
setup.py
src/Makefile
src/Makefile_js
src/apiutil.h
src/movegen.cpp
src/movepick.cpp
src/movepick.h
src/nnue/features/half_ka_v2_variants.cpp
src/parser.cpp
src/position.cpp
src/position.h
src/search.cpp
src/thread.cpp
src/thread.h
src/types.h
src/uci.cpp
src/ucioption.cpp
src/variant.cpp
src/variant.h
src/variants.ini
tests/perft.sh

Add support for squares that are neither accessible nor traversible, using the standard `*` notation.
* Add support for duck chess, closing #528.
* Add support for wall squares, e.g., Gustav III chess, closing #53.
* Refactor game of the amazons to use wall squares.
* This changes both the FEN and move representation.
* Enable -DALLVARS for both pyffish and ffishjs.
Note: With this commit `pieces() == pieces(WHITE) | pieces(BLACK)` can no longer be assumed due to the possibility of wall squares.

Support wall squares

---

src/variants.ini

'mandatoryPiecePromotion = true'
Added this.
In fact, it doesn't affect the game even if it exists, but I thought it would be better to have it, so I added it.

Added promotion duty to Mansindam

---

README.md
src/nnue/nnue_common.h
src/piece.cpp
src/syzygy/tbprobe.cpp
src/tune.h
src/variant.cpp
src/variants.ini
tests/js/README.md
tests/js/test.js
tests/reprosearch.sh

I put isolation, joust, snailtrail under ALLVARS at first to be on the safe side. I haven't seen any problems, so am requesting enabled by default. The most intensive would be Isolation 7x7, which has 360 possible moves at most, which still looks ok.

move isolation, joust, snailtrail to default build. fix typos

---

src/parser.cpp
src/position.cpp
src/variant.h
src/variants.ini

The interaction between Blast and Petrify:
If no special effort, then each piece in the blast will be petrified. This differs from Nuclear rules, where only ground zero is petrified. So petrifyBlastPieces was made to toggle this. It is set to true by default, in case anyone was depending on the previous behaviour.

add Nuclear

---

src/movegen.cpp
src/parser.cpp
src/position.cpp
src/position.h
src/variant.cpp
src/variant.h
src/variants.ini
src/xboard.cpp

1. cfour-misere (All connection win conditions can use connectValue. I suppose it's possible for a variant to have one type of connection a loss and another type a win. but that is a stretch and can be handled as it comes up.)
2. Per-color passing for Marco's variant (no variant included to use it specifically)

Cfour-misere, per-color passing

---

src/Makefile

in case the base infrastructure for providing the networks
https://tests.stockfishchess.org/nns
is down, use an alternate github repo for downloading networks during the build.
No functional change

Provide network download fallback

---

setup.py
src/parser.cpp
src/position.cpp
src/pyffish.cpp
src/variant.cpp
src/variant.h
src/variants.ini
test.py

Adjudicate when board is full

---

src/bitboard.cpp
src/variants.ini
test.py

Adjust movement of flying cannons

Fix cannonshogi

---

tests/js/package.json

Release files are available at:
https://www.npmjs.com/package/ffish-es6

Bump version (0.7.5)

---

src/movegen.h
src/types.h

#583 .
After this change, added a macro definition that can switch the preference whether to put the move list in stack or in heap. Now given the following commands:
```
uci
setoption name UCI_Variant value gustav3
position fen arnbqkbnra/*ppp1pppp*/*3p4*/*8*/*8*/*N1P5*/*PP1PPPPP*/AR1BQKBNRA b KQkq - 0 2 moves f7f5 f2f3 d8e7 e2e4 i7i5 i2i4 j8g5 c2c3 c8d6 a1c2 h8g6 c2d2 f5f4 h1f2 e6e5 j1g4 b7b6 g4g5 e7g5 f2g4 a8b7 d2f2 d6f7 d3d4 d7d6 b3d2 b7d8 d1b3 c7c5 e1e2 g5h4 g2g3 h4e7 f2h3 f7g5 h3h5 g8b3 d2b3 d8f7 b3d2 b6b5 b1d1 g6h8 h5f7 h8f7 f1g2 c5d4 c3d4 b8c8 g1f2 f7h6 d4e5 h6g4 f3g4 d6e5 d2f3 f8h8 f3g5 e7g5 g3f4 g5f4 d1d6 h7h6 d6d5 c8c4 b2b3 c4c3 d5d3 c3d3 e2d3 e8c8 g2h3 g8d8 d3b5 c8c2 f2g3 d8d3 i1g1 d3b3 b5f1 c2e4 f1d1 b3d3 d1b1 h8i7 g1d1 f4d2 b1b2 e4e2 b2b7 i7h7 d1g1 e5e4 g1g2 e2f3 b7b5 d2g5 …
```

Fix stack overflow when depth is too deep

---

src/variants.ini

As described here
https://www.chessvariants.com/diffobjective.dir/giveaway.html
> "More interesting seems Anders Ebenfelt's variant:
> 
>     When stalemate, the stalemated player does not move but the opponent can if he wish to play for win go on moving and do as many moves he wants to do. If the stalemate then disappear, both players move again as usual. So, if white for example has a pawn on h2 and nothing more and black a pawn on h3, pawn on a7 and rooks on a8 and h8 black can win by moving : 1.-,Rh4 2.-, a5. 3.-, a4 4.- Ra5 5.-,a3 6.-,a2 7.-,a1=R 8.-,Rg1 9.-,Rg3 10.hxg3,h2 11.gxh4,Rg5 12.hxg5,h1=Q 13.g6,Qh7 14.gxh7 and black has won.
> 
>     This variant has the advantage that there is often dangerous to let the opponent take all pieces but one if the one left is a pawn which can be …

Small contribution on a compatible anti/giveaway variant

---

src/position.cpp
test.py

Fix duck chess en passant FEN setup

---

.github/workflows/ffishjs.yml

After this change, I created a new job in ffishjs.yml to automatically build and upload ffish.js so that ffish.js can be built automatically in the CI environment. I used the custom build in [https://github.com/yjf2002ghty/Fairy-Stockfish/blob/make_js/.github/workflows/make_js.yml](https://github.com/yjf2002ghty/Fairy-Stockfish/blob/make_js/.github/workflows/make_js.yml) and it works in fairyground by replacing the node module with the custom build. This can avoid setting up environment and build it on our machine and thus saving time.

Upload artifacts for ffish.js builds in CI

---

setup.py
src/position.cpp
src/position.h
src/pyffish.cpp
test.py

To prevent leaking FEN info in Fog of War games to the client side, the only correct solution is to create the "visible" FEN on the server side and send only that to the browser.

Implement fog_fen()

---

.github/workflows/ffishjs.yml
.github/workflows/release.yml
.github/workflows/wheels.yml

**build (12.x)**
Your workflow is using a version of actions/cache that is scheduled for deprecation, actions/cache@v2. Please update your workflow to use either v3 or v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
**Deprecation notice: v1, v2, and v3 of the artifact actions**
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "fairy-stockfish".
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Update workflow action version

---

setup.py

Uploading pyffish to pypi.org fails atm:
```
Uploading pyffish-0.0.85-cp310-cp310-macosx_10_14_x86_64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 576.5/576.5 kB • 00:00 • 1.0 MB/s
INFO     Response from https://upload.pypi.org/legacy/:                                                                                             
400 'License :: OSI Approved :: GNU General Public License v3 or later (GPL-3.0-or-later)' is not a valid classifier. See                  
https://packaging.python.org/specifications/core-metadata for more information.                                                            
INFO     <html>                                                                                                                                     
<head> …
```

Fix pyffish License classifier

---

src/position.h

Pick the frontmost piece to be captured.
Closes #876.

Fix custom ep captures

---

src/endgame.cpp

- In the first if statement of the diff, `if (pos.side_to_move() == strongSide && (attacks_bb<KNIGHT>(NSq) & KSq))` is a bug. I think the intention is to see if the king is attacking the knight, so I fixed it to that.
- In some cases where the king is to move and it's on the edge (e.g., Kg1 and Ne2), the knight attacking the king actually does mean that the knight wins (but only if the king is not attacking any other squares the knight attacks). So I rewrote the code to handle all cases where the king and knight attack each other or share attacks.
Briefly tested with a few positions, but haven't done a fishtest (http://www.variantfishtest.org:6543/tests doesn't load for me).

Fix bug with antichess K vs N
