- src/search.cpp
- src/thread.h
- src/types.h
- src/uci.cpp
- src/uci.h
- src/ucioption.cpp
- src/variant.cpp
Implements CECP/XBoard as third supported protocol besides UCI and USI.
Since I am not an expert on the CECP protocol, independent testing or review is very welcome. So far I tested analysis and game play with XBoard and cutechess for a few variants, which seems to be working fine.
Implementation is based on specification in https://www.gnu.org/software/xboard/engine-intf.html#8.
> Support XBoard protocol (close #37)

- src/evaluate.cpp
- src/parser.cpp
- src/piece.cpp
- src/position.cpp
- src/position.h
- src/psqt.cpp
- src/types.h
- src/variant.cpp
- src/variant.h
- src/variants.ini
- tests/perft.sh
https://en.wikipedia.org/wiki/Ataxx
bench: 5499014
> Support Ataxx

- .travis.yml
- Readme.md
- src/Makefile
- src/movegen.cpp
- src/parser.cpp
- src/piece.cpp
- src/position.cpp
- src/position.h
- src/types.h
- src/uci.cpp
- src/variant.cpp
- src/variant.h
- src/variants.ini
- tests/perft.sh
https://en.wikipedia.org/wiki/Game_of_the_Amazons
> Support Game of the Amazons

- src/evaluate.cpp
Add a penalty for pieces in hand if there are not enough gates left.
> Evaluate ungatable pieces in Seirawan

- src/apiutil.h
- src/ffishjs.cpp
- tests/js/README.md
- tests/js/package.json
- tests/js/test.js
- tests/pgn/pychess-variants_zJxHRVm1.pgn
Hello @gbtami and @ianfab ,
this PR fixes the issue from #204.
* Added test for loading Seirawan chess pgn
* Updated README.md
* Updated **ffish** to **0.4.6**
> Updated ffish.js to 0.4.6, fixes game header parsing

- src/partner.cpp
- src/search.cpp
- src/thread.cpp
- src/thread_win32_osx.h
- src/uci.cpp
- src/xboard.cpp
- src/xboard.h
Refactor handling of protocol state for CECP and implement pondering.
Improves the protocol compliance of several commands along the way.
Closes #103.
> Support pondering in CECP

- .github/workflows/ffishjs.yml
- src/Makefile_js
- tests/js/README.md
- tests/js/package.json
- Add Makefile for easier compilation
- Run js unit tests as part of CI
> Add workflow for ffishjs

- tests/js/package.json
- tests/js/test.js
+ added unit test for atomic(960) castling rights by @gbtami (fixes #267).
> Updated ffish.js to 0.6.1

- src/apiutil.h
- src/ffishjs.cpp
- src/position.cpp
- src/pyffish.cpp
- src/variant.cpp
- test.py
- tests/js/test.js
- Support X-FEN validation
- Support fetching variant list in pyffish
- Use variant configuration properties more consistently
- Fix a few corner cases
- Improve test coverage
- More consistent formatting
Still missing:
- Validation of S-Chess and Ouk gating ("castling") info
> Refactor FEN validation

- src/piece.cpp
- src/piece.h
> Define piece types via Betza notation

- src/bitboard.cpp
- src/parser.cpp
- src/piece.cpp
- src/piece.h
- src/psqt.cpp
> Simplify piece initialization

- src/nnue/features/half_ka_v2_variants.cpp
- src/nnue/features/half_ka_v2_variants.h
- src/variant.h
This enables to consider pieces in hand in NNUE evaluation.
> Support pieces in hand for NNUE

- src/variant.cpp
Loss happens if player fails to change sequence after repeating the same board state 3 times... So nFold actually is 4.
> Corrected Tori n-fold repetiion.

- src/variant.cpp
> Validate variants.ini syntax

- src/apiutil.h
- test.py
> Support validation of lichess 3check FENs

- src/position.cpp
- test.py
- tests/js/test.js
> Remove redundancy from S-Chess FEN

- src/uci.cpp
- src/ucioption.cpp
> Support time unit switch for UCCI

- setup.py
- src/apiutil.h
- src/pyffish.cpp
- test.py
> Disambiguate promotion moves

- src/uci.cpp
- src/uci.h
- src/ucioption.cpp
> Fix option names for UCI dialects

- src/apiutil.h
- src/ffishjs.cpp
- src/position.cpp
- src/position.h
- src/pyffish.cpp
- test.py
- tests/js/test.js
This adds checking for checks on pseudo-royal pieces like in Atomic to pyffish's gives_check and ffish.js's isCheck functions.
> Support checking for checks on pseudo-royal pieces

- .github/workflows/release.yml
- README.md
The build.yml file is renamed to release.yml and it Uploads both linux and windows binaries that can be published in Releases.
> Create a workflow for releases

- tests/js/package.json
Published **ffish.js@0.6.6**.
* https://www.npmjs.com/package/ffish
> Bump ffish to 0.6.6

- src/position.cpp
> Make castling through flying general illegal

- .github/workflows/fairy.yml
- .github/workflows/ffishjs.yml
- .github/workflows/release.yml
- .github/workflows/stockfish.yml
- actions/checkout@v2 to actions/checkout@v3 : https://github.com/actions/checkout/releases/tag/v3.0.0
- actions/upload-artifact@v2 to actions/upload-artifact@v3 : https://github.com/actions/upload-artifact/releases/tag/v3.0.0
> Update GitHub Actions

- src/position.cpp
- tests/perft.sh
Consider pinned rook scenario like in chess960.
Closes #453.
> Fix shako castling

- src/position.cpp
> Consider king checks

- src/bitboard.h
- src/parser.cpp
- src/position.cpp
- src/position.h
- src/types.h
- src/variant.cpp
- src/variant.h
- src/variants.ini
- test.py
- tests/js/test.js
Implements AXF chasing rules, also see #55.
Chasing rules still need to be made configurable, this PR is mainly to collect feedback.
> Support xiangqi chasing rules

- tests/js/package.json
> Bump ffish.js version to 0.6.8

- src/position.cpp
- src/search.cpp
- src/uci.cpp
- src/uci.h
- src/ucioption.cpp
> Convert protocol option to enum

- src/nnue/features/half_ka_v2_variants.cpp
- src/nnue/features/half_ka_v2_variants.h
- src/variant.cpp
- src/variant.h
- src/variants.ini
Also adjust NNUE code for othello and other non-chess variants.
> Add flipello to built-in variants

- src/position.cpp
> Update 50 move rule for xiangqi

- src/movegen.cpp
- src/position.cpp
- test.py
- tests/perft.sh
Article 5, Items 3 and 4
https://docs.google.com/document/d/1adppJ66vonM27UYwC-KyldXl7oZ_5Pb0/edit?usp=sharing&ouid=116281580550740302191&rtpof=true&sd=true
- The king now loses the ability to leap if an enemy rook moves into the same rank or file
- The ferz can no longer capture with its leap
> Implement correct Cambodian opening moves

- tests/js/package.json
See https://github.com/ianfab/Fairy-Stockfish/pull/522.
> Bump ffish version to 0.7.0

- tests/js/package.json
See https://github.com/ianfab/Fairy-Stockfish/pull/553.
New package versions are available at:
https://www.npmjs.com/package/ffish
>  Bump ffish version to 0.7.1

- src/apiutil.h
- src/ffishjs.cpp
- src/pyffish.cpp
- test.py
This adds support for Thai SAN and LAN to the libraries.
> Thai Notations

- src/movegen.cpp
> Consider configured pawn mobility region

- src/position.cpp
> Ignore temporary immobility for immobilityIllegal

- src/position.cpp
- tests/perft.sh
> Correctly restrict to mustDropType

- tests/js/package.json
New package versions are available at:
https://www.npmjs.com/package/ffish
>  Bump ffish version to 0.7.2

- src/movegen.cpp
- src/parser.cpp
- src/position.cpp
- src/position.h
- src/variant.cpp
- src/variant.h
- src/variants.ini
gating could be divided into static gating, and past gating
a couple example variants of how they could be used.
> static and past gating: isolation, joust, snailtrail

- .github/workflows/release.yml
> Fix CI out of memory

- src/apiutil.h
- src/bitboard.h
- src/endgame.cpp
- src/evaluate.cpp
- src/material.cpp
- src/movegen.cpp
- src/nnue/features/half_ka_v2_variants.cpp
- src/parser.cpp
- src/position.cpp
- src/position.h
- src/psqt.cpp
- src/search.cpp
- src/types.h
- src/ucioption.cpp
- src/variant.cpp
- src/variant.h
Simplifies the code and improves performance.
No functional change.
> Replace set<PieceType> by PieceSet enum

- src/apiutil.h
- src/parser.cpp
- src/position.cpp
- src/position.h
- src/variant.cpp
- src/variant.h
- src/variants.ini
- tests/perft.sh
> Support multiple castling rook types

- tests/js/package.json
New package versions are available at:
https://www.npmjs.com/package/ffish
>  Bump ffish version to 0.7.4

- src/position.cpp
> Fix gives_check for cannons

- .github/workflows/release.yml
> Add ALLVARS binary to builds

- src/position.cpp
- src/variant.cpp
- test.py
- tests/js/test.js
Reset 50 move rule counter only in case of irreversible moves.
> Redefine reset of 50 move rule counter

- src/position.cpp
> Do not use 2 fold adjudication for chases

- src/parser.cpp
- src/variants.ini
1D Chess, Tuktuk, Aralzaa, Bajr, Lewthwaite's Game, Hexapawn
I don't expect all to be accepted, just any that are interesting enough.
> add mini games

- src/apiutil.h
- src/evaluate.cpp
- src/nnue/features/half_ka_v2_variants.cpp
- src/parser.cpp
- src/position.cpp
- src/position.h
- src/search.cpp
- src/variant.cpp
- src/variant.h
- src/variants.ini
- tests/perft.sh
Simplify and generalize implementation to support color-specific flag pieces as well as allowing all pieces to be eligible.
> Refactor capture the flag implementation

- src/position.cpp
- src/syzygy/tbprobe.cpp
- src/variants.ini
add Annexation (issue #654). fix typos.
> add Annexation (issue #654). fix typos.

- .github/workflows/stockfish.yml
https://github.com/fairy-stockfish/Fairy-Stockfish/actions/runs/5916934063/job/16044755052
also see https://github.com/orgs/community/discussions/63391
> Upgrade Ubuntu version for CI

- src/variants.ini
better follows the information in this message: https://discord.com/channels/634298688663191582/634327888275177482/1136516400345780264
> Fix "xiangqihouse" to Align with Actual Xiangqi Bughouse

- src/variants.ini
Disable promotions for Caught-in-a-snag
> Fix promotion rules of Caught-in-a-snag variant

- src/apiutil.h
- src/movegen.cpp
- src/parser.cpp
- src/position.cpp
- src/position.h
- src/search.cpp
- src/uci.cpp
- src/variant.cpp
- src/variant.h
- src/variants.ini
not expecting ducktest to actually be added, just for testing.
> add Duck region mask. add ducktest. add forward/checkers

- src/position.cpp
Try to avoid crashing on FENs with wrong board size and parse them to the extent possible.
Example:
```
position fen k////KPPPPPPPPPPPPPPP/N6NN/8B/Q
d
+---+---+---+---+---+---+---+---+
| k |   |   |   |   |   |   |   |8  
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |7
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |6
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |5
+---+---+---+---+---+---+---+---+
| K | P | P | P | P | P | P | P |4
+---+---+---+---+---+---+---+---+
| N |   |   |   |   |   |   | N |3
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |2
+---+---+---+---+---+---+---+---+
| Q |   |   |   |   |   |   |   |1 *
+---+---+---+---+---+---+---+---+
a   b   c   d   e   f   g   h
Fen: …
```
> Handle FENs with wrong board size

- src/parser.cpp
- src/position.h
- src/variant.h
- src/variants.ini
add flagPieceSafe option. rework Alapo to use it.
add Squatter as another use of flagPieceSafe.
> flagPieceSafe, Squatter

- src/variant.cpp
See in https://github.com/gbtami/pychess-variants/issues/1338#issuecomment-2018334956
> Add missing dragon promotion

- src/position.cpp
- src/variants.ini
was able to trigger the asserts and fix them
> wallOrMove bug fix

- src/variants.ini
Add Khan's chess & Shinobi Chess+ from PyChess to variants.ini
> Khan's chess & Shinobi Chess+

- src/variants.ini
> Fix Mini House

- .github/workflows/stockfish.yml
- src/Makefile
https://github.com/fairy-stockfish/Fairy-Stockfish/issues/464
Separated from #792 .
After this change:
1. Added `-fno-strict-aliasing` when `optimize=yes`
2. Added 2 tasks in the Continuous Integration to check this kind of error.
> Fix assertion error when debug=yes and optimize=yes

- src/variants.ini
a variant Muje has been added
Could you please add Muje to variants.ini? (Muje means Untitled)
> Update variants.ini (+ Muje)

- src/variants.ini
I created a chess variant called Leaperhouse. Could you please add this variant ?
> Update variants.ini (+ Leaperhouse)

- src/position.cpp
- test.py
> Handle invalid castling FEN

- src/position.cpp
- test.py
> Fix FEN parsing for S-Chess

- setup.py
- src/pyffish.cpp
- tests/js/package.json
Fixes https://github.com/gbtami/pychess-variants/issues/1789
> Bump versions

- .github/workflows/fairy.yml
- .github/workflows/ffishjs.yml
- .github/workflows/release.yml
- .github/workflows/stockfish.yml
- .github/workflows/wheels.yml
- src/position.cpp
Added macOS builds for `x84-64` and `apple-silicon`.
`x86-64` build settings previously confirmed to work [on discord](https://discord.com/channels/779317816897699850/791247944463417374/1304107662375653489).
> macOS builds + Runner updates

- src/position.cpp
- test.py
> Validate drops of pseudo-royals
